### PR TITLE
update ci build to use JDK8

### PR DESCRIPTION
**Pull request by jtnord**
Updates the Jenkinsfile to use JDK8 for the builds.

@reviewbybees   Blocked by #23

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
I'd rather 🐛 it till Jenkins project drops Java 7. Just because it may capture some additional issue.

**Comment by jglick** [comment]
@oleg-nenashev why? We run most component builds on JDK 8, and rely on `-target` and Animal Sniffer to detect issues.

**Comment by oleg-nenashev** [comment]
@jglick But do we have Animal Sniffer in this component? From what I see "no"

**Comment by jglick** [comment]
I will deal with that, just a minute…

**Pull request merged**
