### PR TITLE
[JENKINS-52121] - Add sessionEviction to help text

### PR DESCRIPTION
**Pull request by huggsboson**

### CODE REVIEW

**Comment by huggsboson** [comment]
Do I need to sign some sort of CLA?

**Comment by huggsboson** [comment]
@oleg-nenashev anything else I need to do?

**Comment by huggsboson** [comment]
Zero urgency.

**Comment by oleg-nenashev** [comment]
Thanks for catching it anyway!
I have created https://issues.jenkins-ci.org/browse/JENKINS-52121. In order to reduce the release process overhead will ship along with another patches once we have them.

**Pull request merged**
