### PR TITLE
[JENKINS-57888] - Restore `java.util.logging.config.file` property support (regression in 5.4)

### PR DESCRIPTION
**Pull request by lrpg**
See [JENKINS-57888](https://issues.jenkins-ci.org/browse/JENKINS-57888).

### Proposed changelog entries

* Logging: Specifying -Djava.util.logging.config.file makes the specifying of a ConsoleHandler possible, which was not possible anymore since winstone 5.4

### Proposed upgrade guidelines

N/A

### Submitter checklist

- [x] JIRA issue is well described
- [x] Changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developer, depending on the change). [Examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)
  * Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
- [x] Appropriate autotests or explanation to why this change has no tests
- [x] For dependency updates: links to external changelogs and, if possible, full diffs

### Desired reviewers

@jglick 

### Maintainer checklist

Before the changes are marked as `ready-for-merge`: 

- [ ] There are at least 2 approvals for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [ ] Changelog entries in the PR title and/or `Proposed changelog entries` are correct
- [ ] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional upgrade steps from users, `upgrade-guide-needed` label is set and there is a `Proposed upgrade guidelines` section in the PR title. ([example](https://github.com/jenkinsci/jenkins/pull/4387))
- [ ] If it would make sense to backport the change to LTS, a JIRA issue should exist and be labeled as `lts-candidate`

### CODE REVIEW

**Comment by lrpaquet-jive** [comment]
> Sounds straightforward. Does it work?

I tested it outside of context and it works.
I wanted some feedback first.

I still need to build jenkins to test the full loop to be absolutely sure it will work.
Is it necessary?

**Comment by lrpaquet-jive** [comment]
Just tested it and it works.

We'll still have to be careful as command line arguments like

-Djava.util.logging.ConsoleHandler.* will be ignored.

**Comment by lrpg** [comment]
Just tested it and it works.

We'll still have to be careful as command line arguments like

-Djava.util.logging.ConsoleHandler.* will be ignored.

**Comment by oleg-nenashev** [comment]
I plan to merge it tomorrow if no negative feedback

**Comment by lrpg** [comment]
Will you release Winstone and integrate it into the next Jenkins weekly or do I have steps to do?

**Comment by oleg-nenashev** [comment]
@lrpg Thanks, no extra actions needed from your side

**Comment by oleg-nenashev** [comment]
Sorry for the delay with the release. There were some unexpected issues with the Jenkins weekly, and we finally ended up with cutting an out-of order Jenkins 2.217 release. See https://groups.google.com/forum/#!topic/jenkinsci-dev/rcABNLJOAkA for the context.

On Wednesday Winstone release failed for me, and I was unable to get it in time into the master branch. I will try to get a pull request staged

**Pull request merged**
