### PR TITLE
Introduce Winstone Bill of Materials

### PR DESCRIPTION
**Pull request by oleg-nenashev**
This PR introduces Winstone BOM and also parent POM that glues components together

## Why?

* Currently Jenkins Winstone is not expanded in [Jenkins BOM](https://github.com/jenkinsci/jenkins/tree/master/bom). It leads to continuous misconnect between Jetty and Jetty Maven Versions we use.
* It also complicates handling of Jetty in alternate Jenkins packaging like Jenkinsfile Runner (https://github.com/jenkinsci/jenkinsfile-runner/issues/530)
* Last but not least, Jenkins `/about` page could be more explicit about which components are included into Jenkins via Winstone inclusion into WAR's classpath

### CODE REVIEW

**Comment by timja** [comment]
needs fixing

**Comment by oleg-nenashev** [comment]
FTR

```
[2021-10-17T16:44:50.478Z] [ERROR] Failed to execute goal org.codehaus.mojo:flatten-maven-plugin:1.2.7:flatten (flatten) on project winstone: 12 problems were encountered while building the effective model for org.jenkins-ci:winstone:5.22-rc626.4e6ad8f665b4

[2021-10-17T16:44:50.478Z] [ERROR] [WARNING] 'build.plugins.plugin.version' for org.codehaus.mojo:flatten-maven-plugin is missing. @ org.jenkins-ci:winstone:${revision}${changelist}, /home/jenkins/workspace/Core_winstone_PR-172/winstone/pom.xml

[2021-10-17T16:44:50.478Z] [ERROR] [ERROR] 'dependencies.dependency.version' for org.eclipse.jetty:jetty-server:jar is missing. @ 

[2021-10-17T16:44:50.478Z] [ERROR] [ERROR] 'dependencies.dependency.version' for org.eclipse.jetty:jetty-util:jar is missing. @ 

[2021-10-17T16:44:50.478Z] [ERROR] [ERROR] 'dependencies.dependency.version' for org.eclipse.jetty:jetty-servlet:jar is missing. @ 

[2021-10-17T16:44:50.478Z] [ERROR] [ERROR] 'dependencies.dependency.version' for org.eclipse.jetty:jetty-webapp:jar is missing. @ 

[2021-10-17T16:44:50.478Z] [ERROR] [ERROR] 'dependencies.dependency.version' for org.eclipse.jetty.http2:http2-server:jar is missing. @ 

[2021-10-17T16:44:50.478Z] [ERROR] [ERROR] 'dependencies.dependency.version' for org.eclipse.jetty.http2:http2-hpack:jar is missing. @ 

[2021-10-17T16:44:50.478Z] [ERROR] [ERROR] 'dependencies.dependency.version' for org.eclipse.jetty:jetty-alpn-server:jar is missing. @ 

[2021-10-17T16:44:50.478Z] [ERROR] [ERROR] 'dependencies.dependency.version' for org.eclipse.jetty.alpn:alpn-api:jar is missing. @ 

[2021-10-17T16:44:50.478Z] [ERROR] [ERROR] 'dependencies.dependency.version' for org.eclipse.jetty:jetty-jmx:jar is missing. @ 

[2021-10-17T16:44:50.478Z] [ERROR] [ERROR] 'dependencies.dependency.version' for org.eclipse.jetty.websocket:websocket-server:jar is missing. @ 

[2021-10-17T16:44:50.478Z] [ERROR] [ERROR] 'dependencies.dependency.version' for io.jenkins.lib:support-log-formatter:jar is missing. @

[2021-10-17T16:44:50.478Z] [ERROR] -> [Help 1]

[2021-10-17T16:44:50.478Z] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:flatten-maven-plugin:1.2.7:flatten (flatten) on project winstone: 12 problems were encountered while building the effective model for org.jenkins-ci:winstone:5.22-rc626.4e6ad8f665b4

[2021-10-17T16:44:50.478Z] [WARNING] 'build.plugins.plugin.version' for org.codehaus.mojo:flatten-maven-plugin is missing. @ org.jenkins-ci:winstone:${revision}${changelist}, /home/jenkins/workspace/Core_winstone_PR-172/winstone/pom.x
```

**Comment by basil** [comment]
> Currently Jenkins Winstone is not expanded in [Jenkins BOM](https://github.com/jenkinsci/jenkins/tree/master/bom). It leads to continuous misconnect between Jetty and Jetty Maven Versions we use.

If you are referring to the disconnect between `org.jenkins-ci:winstone` and `org.eclipse.jetty:jetty-maven-plugin`, then this PR will not solve that problem. This PR does not define a version for `org.eclipse.jetty:jetty-maven-plugin`, and even if it did, it would not be available from a `<pluginManagement>` or `<plugins>` section in a consumer (which is where that version would need to be consumed).

**Comment by basil** [comment]
I suggest this PR be closed, as I do not think it accomplishes what it says it is trying to accomplish for the reasons given in https://github.com/jenkinsci/winstone/pull/172#issuecomment-1032141527.

**Comment by basil** [comment]
Closing this PR, as pending [MNG-2496](https://issues.apache.org/jira/browse/MNG-2496) it does not seem to have any practical use case.

**Pull request closed without merging**
