### PR TITLE
[JENKINS-68694] Bump Jetty from 9.4.48.v20220622 to 10.0.11

### PR DESCRIPTION
**Pull request by basil**
Do _not_ review. Merely filing this PR to have a record of a timestamped snapshot I just deployed. The timestamped snapshot is available here:

- https://repo.jenkins-ci.org/snapshots/org/jenkins-ci/winstone/5.22-SNAPSHOT/winstone-5.22-20211219.204048-2.jar
- https://repo.jenkins-ci.org/snapshots/org/jenkins-ci/winstone/5.22-SNAPSHOT/winstone-5.22-20211219.204048-2-sources.jar

### CODE REVIEW

**Comment by olamy** [comment]
what is this PR?? duplicate of https://github.com/jenkinsci/winstone/pull/181 ??

**Comment by basil** [comment]
> what is this PR?? duplicate of #181 ??

Please see the PR description:

> Do _not_ review.

**Comment by olamy** [comment]
I was happy to continue the work I started here https://github.com/jenkinsci/winstone/pull/181
why keep having a parallel PR?

**Comment by basil** [comment]
> why keep having a parallel PR?

@olamy Please see the PR description:

> Do _not_ review.

**Comment by olamy** [comment]
frankly would be better to work as a community and maintaining a single PR

**Pull request closed without merging**
