### PR TITLE
[JENKINS-61823] - Fix '--httpKeepAliveTimeout' option which had no effect in 5.9

### PR DESCRIPTION
**Pull request by olamy**
Signed-off-by: olivier lamy <olamy@apache.org>

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
FYI @jenkinsci/core-pr-reviewers . It will need expedited fix in weekly and backporting to LTS (.3 or maybe even a .2 one)

**Comment by res0nance** [comment]
One question is that if someone sets `-keepAliveTimeout` and after this patch it will stop working? was this option available before?

**Comment by jglick** [comment]
> make this field `private` so it does not appear in `all()` and is thus not publicized

Note that the same applies to `_LISTEN_ADDRESS` and `_PORT`. The situation is different for those in that while the option always existed, it was also ignored.

**Comment by olamy** [comment]
@res0nance @jglick I don't understand your request.  AFAIK and looking in history `--KeepAliveTimeout ` has **NEVER** been accepted and never used as an argument....
So I don't understand why adding this new option now as we just want to fix a bug due to a recent  change? (https://github.com/jenkinsci/winstone/commit/5e1a8982f1412cacbe3bc4d0feb29436918bf8be#r38330848 and https://github.com/jenkinsci/winstone/commit/5e1a8982f1412cacbe3bc4d0feb29436918bf8be#r38330929 )

**Comment by jglick** [comment]
It _is_ accepted. All `public` option fields are. Try it.

**Comment by olamy** [comment]
What I mean is "this option has never been parsed/used to set any configuration". It has never have any effect. It's not documented here https://github.com/jenkinsci/winstone neither here https://github.com/jenkinsci/winstone/blob/master/src/main/resources/winstone/LocalStrings.properties.
 It's here because... I don't know :) (maybe to avoid a copy/paste of the String..)

**Comment by jglick** [comment]
> It has never had any effect.

Until 5.9, evidently.

> `--KeepAliveTimeout ` has **NEVER** been accepted and never used/parsed as an argument

I am afraid that is not true.

```console
$ java -jar ~/.m2/repository/org/jenkins-ci/main/jenkins-war/2.204.1/jenkins-war-2.204.1.war --Bogus=99
Running from: /home/jglick/.m2/repository/org/jenkins-ci/main/jenkins-war/2.204.1/jenkins-war-2.204.1.war
webroot: $user.home/.jenkins
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at Main._main(Main.java:375)
	at Main.main(Main.java:151)
Caused by: java.lang.IllegalArgumentException: Unrecognized option: --Bogus=99
	at winstone.cmdline.CmdLineParser.parse(CmdLineParser.java:52)
	at winstone.Launcher.getArgsFromCommandLine(Launcher.java:371)
	at winstone.Launcher.main(Launcher.java:342)
	... 6 more
$ java -jar ~/.m2/repository/org/jenkins-ci/main/jenkins-war/2.204.1/jenkins-war-2.204.1.war --KeepAliveTimeout=99
Running from: /home/jglick/.m2/repository/org/jenkins-ci/main/jenkins-war/2.204.1/jenkins-war-2.204.1.war
webroot: $user.home/.jenkins
2020-04-07 22:40:11.914+0000 [id=1]	INFO	org.eclipse.jetty.util.log.Log#initialized: Logging initialized @247ms to org.eclipse.jetty.util.log.JavaUtilLog
2020-04-07 22:40:11.989+0000 [id=1]	INFO	winstone.Logger#logInternal: Beginning extraction from war file
…
```

> neither documented as such

Correct.

**Comment by jglick** [comment]
So to be clear I recommend simply making the three option fields starting with `_` be `private`, preventing them from being accepted as options.

**Comment by timja** [comment]
@olamy / @oleg-nenashev any reason this wasn't released?

(someone asked about it in IRC)

**Comment by oleg-nenashev** [comment]
No reason. I will trigger the release now

**Comment by oleg-nenashev** [comment]
done

**Pull request merged**
