### PR TITLE
JDK-8239027 is in JDK 8u252

### PR DESCRIPTION
**Pull request by jglick**

### CODE REVIEW

**Comment by nthung82** [comment]
i had commandline: java -jar myapp.jar
and my java:
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)

**Comment by nthung82** [comment]
help me?

**Comment by olamy** [comment]
@nthung82 I'm happy to help but what is your problem exactly? can you describe your problem? And by the way please create an issue https://www.jenkins.io/participate/report-issue/ or ask your question to the user list see https://www.jenkins.io/mailing-lists/.
But please do not use this pull request to do it!

**Comment by nthung82** [comment]
https://webtide.com/jetty-alpn-java-8u252/
i am fflowing
that link for java open jdk8 252
but not ok

**Comment by olamy** [comment]
I still don't understand what you are doing or wants to achieve?
Again this PR is not the place to ask questions so please create an issue in Jira.

**Pull request merged**
