### PR TITLE
add a Jenkinsfile

### PR DESCRIPTION
**Pull request by jtnord**
@reviewbybees /cc @rtyler

### CODE REVIEW

**Comment by jtnord** [comment]
@rtyler you can not build this with JDK8 - the code used to build the self signed certificates was (re)moved with JDK8.   ([JENKINS-25333](https://issues.jenkins-ci.org/browse/JENKINS-25333))

**Comment by rtyler** [comment]
That's fun. At some point in 2017, JDK7 support is going to likely disappear from Jenkins infrastructure entirely, as Jenkins itself moves away from it.

*shrugs*

**Comment by jglick** [comment]
Then let us merge #23 first. I do not think we should be building anything on JDK 7 at this point.

**Comment by jtnord** [comment]
@jglick Well I gathered from the feedback that #23 is not currently merge-able.
Lets do this and we can trivially bump the JDK version after?

Currently winstone is not building for me and I would like to rule environmental issues vs its just not working on windows issues.

**Pull request merged**
