### PR TITLE
[FIXED JENKINS-39436] set/unset server version support

### PR DESCRIPTION
**Pull request by escoem**
please @reviewbybees cc. @aheritier @daniel-beck

### CODE REVIEW

**Comment by aheritier** [comment]
🐝

**Comment by daniel-beck** [comment]
https://wiki.jenkins-ci.org/display/JENKINS/GitHub+commit+messages

**Comment by daniel-beck** [comment]
The issue does not present a rationale for this change, making it impossible to judge the value of this change, so :-1: out of principle.

Depending on the reason for this change, maybe we don't need an option at all, and could just always set this flag? Again, impossible to evaluate because the ticket is useless.

**Comment by escoem** [comment]
@daniel-beck I have updated the JIRA issue https://issues.jenkins-ci.org/browse/JENKINS-39436

This PR provides a configuration option for unset the HTTP response header.

Server: Jetty(9.2.z-SNAPSHOT)

**Comment by amuniz** [comment]
@daniel-beck in general any security analysis will suggest to hide any information that could give opportunities to an attacker, and server name and version is a good clue for them.

Giving the option to hide the `Server` header is something a lot of people is doing by setting up another network element in front of Jenkins, but why should we require that? Specially if Jetty is already giving us the option to do it.

I'm :+1: on this change (and leave everything as it is now by default, so we avoid any possible backward issue).

**Comment by daniel-beck** [comment]
@amuniz 

> hide any information that could give opportunities to an attacker, and server name and version is a good clue for them

In general, yes. But Jetty is, very publicly, the default container for Jenkins. And Jenkins is trivial to detect by its headers. How does this slow anyone down even a bit?

---

Does this at least remove the server signature from 404 error pages as wekk, or does it only take a single request to a non-existing resource to still see the following, despite this change?

> Powered by Jetty://

**Comment by oleg-nenashev** [comment]
@amuniz @escoem this PR is waiting for your response

**Comment by amuniz** [comment]
@daniel-beck @oleg-nenashev hiding the server is like a good security practice in general, I don't see a reason to not apply this (although I don't see it as something really important), so up to you.

**Comment by daniel-beck** [comment]
@amuniz No response to the second half of my previous comment. If that's not also addressed, applying this would be a joke. Otherwise, we can (and could even default to false IMO, not opposed).

**Comment by daniel-beck** [comment]
@escoem Merge conflict.

**Comment by oleg-nenashev** [comment]
Added issue labels. @escoem @aheritier  any plans to work on it?

**Comment by daniel-beck** [comment]
Nothing changed since my previous comments.

**Comment by escoem** [comment]
@oleg-nenashev @aheritier @daniel-beck does fixing the merge conflict make sense?

**Comment by oleg-nenashev** [comment]
I think this change is not going to solve any security concern in general. Security through obscurity, but OTOH I agree with @aheritier that it's a common practice. If the PR is finalized and confirmed to work properly, I am fine with this change.

**Pull request closed without merging**
